- name: enable-proxy-config
  shell: cat proxy.conf
  notify:
  - restart-apache

- name: restart-httpd
  service: name=httpd state=restarted

- name: restart-vsftpd
  service: name=vsftpd state=restarted
