- name: "Installing Software"
  yum: pkg={{ item }} state=installed
  with_items:
  - vim
  - nmap
  - git
  - libselinux-python
- name: "Copy ntp config"
  copy: src=/home/mku/ansible/ntp.conf dest=/etc/ntp.conf owner=root group=root mode-0644

- name: "Copy files"
  copy: src=/home/mku/readme dest=/home/mku/readme owner=root group=root mode-0644

- name: "Copy file time zone and restart ntpd"
  copy: src=/usr/share/zoneinfo/Europe/Kiev dest=/etc/localtime owner=root group=root mode-0644
  notify:
  - restart-ntpd  
