- name: "Installing Software"
  yum: pkg={{ item }} state=installed
  with_items:
  - vim
  - nmap
  - git
  - libselinux-python
  - vsftpd
  - ftp

- name: "copy cfg and restart FTPd"
  copy: src=../files/vsftpd.conf dest=/etc/vsftpd/vsftpd.conf owner=root group=root mode-0644
  notify:
  - restart-vsftpd

- name: "Copy ntp config"
  copy: src=/home/mku/ansible/ntp.conf dest=/etc/ntp.conf owner=root group=root mode-0644

- name: "Copy files"
  copy: src=/home/mku/readme dest=/home/mku/readme owner=root group=root mode-0644

- name: "Copy file time zone and restart ntpd"
  copy: src=/usr/share/zoneinfo/Europe/Kiev dest=/etc/localtime owner=root group=root mode-0644
  notify:
  - restart-ntpd 

- name: "adding IP to /etc/hosts" 
  lineinfile: name=/etc/hosts line="172.16.10.95 mkubuntu"
